### ISSUE TITLE
Fix documentation for `expect`

### ISSUE THREAD

**Issue by spenserblack** [DanielKeep/rust-boolinator#7]
Documentation for `expect` says
>If this value is `true`, panics with `msg`; does nothing otherwise.

But it [actually panics on `false`](https://docs.rs/boolinator/2.4.0/src/boolinator/lib.rs.html#157)

**Comment by spenserblack** [comment]
Sorry, just saw this was already fixed.

**Comment by joshtriplett** [comment]
https://github.com/DanielKeep/rust-boolinator/issues/8
